### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [sadellie/unitto#1]
Would you consider publishing this app on F-Droid please?

RFP: https://gitlab.com/fdroid/rfp/-/issues/2148

**Comment by sadellie** [comment]
Hello. Unitto is almost at the end of support. There are only 2 major updates planned. The first one will be released this week. The second one will be released next month. 
There will not be any updates after stable release of the second major update.

I do not oppose the inclusion, but have no plans on uploading it myself. You are free to fork this repo, fix errors from [F-Droid Bot](https://gitlab.com/fdroid/rfp/-/issues/2148#note_1039837283) and upload it.

**Comment by sadellie** [comment]
Ok, I will see if I can add new flavor without breaking anything in the app.

**Comment by sadellie** [comment]
Added:
1. "fdroid" flavor without Firebase dependencies
2. Files for Fastlane

Hope that everything is ok now!

**Comment by IzzySoft** [comment]
Waiting for the next tag then (please ping the RFP when it's there).

Hint: If you leave out [the `/ru` part here](https://github.com/sadellie/unitto#L102), language will be chosen automatically based on the user's locale. Plus the link would open in the F-Droid app, should it be installed and the user decides so.

**Comment by IzzySoft** [comment]
Also wondering about the "not planned" – while in parallel an inclusion request is processed, in which you're [even involved](https://gitlab.com/fdroid/rfp/-/issues/2148#note_1045851171) :wink: Maybe you wanted to close a totally different issue instead (in a different project even, as here's no other issue open), and just hit the wrong browser tab?

**Comment by sadellie** [comment]
Got confused with different buttons. Sorry, I'm kinda noob with GitHub.

**Comment by shuvashish76** [comment]
Live on F-Droid: https://f-droid.org/packages/com.sadellie.unitto/

Badges : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

> Edit: Currently supporting the app. New updates are planned.

Thanks for reconsidering app maintenance.
