### ISSUE TITLE
Spanish translation broken

### ISSUE THREAD

**Issue by edilberto507h** [sadellie/unitto#100]
Hello, just installed your app, and notice that the app in fdroid page is missing some of the languages, and in the github one the Spanish translation is broken, the name of some of the units names, and the app interface are staying in English.

😢

**Comment by sadellie** [comment]
Could you please provide an example of untranslated text in the app? Maybe it's not translated yet.

**Comment by edilberto507h** [comment]
Listing what I found that don't translate.

Setting screen and sub screens, stay in English
In main window, the left panel stay in English
In Unit selection screen the title, the unit group names stay in English
units in: 
The Units in the following groups Area, Acceleration, Angle, Flow, Fuel, all stay in English
Volume group some units doesn't translate like:
Cubic centimeter
Cubic meter
Cubic millimeter
Cubic Kilometer
Imperials (all units)
US tablespoon
Us teaspoon

I tested changing the language to French, Italian, Deutsche, and every works fine.

**Comment by sadellie** [comment]
Spanish translation is 40% complete. There are more than 1300 strings in the app, so it will take some time to translate everything
