### ISSUE TITLE
[Bug] There is a bug in app opening Animation in the latest version 

### ISSUE THREAD

**Issue by Sureshgorai25** [sadellie/unitto#102]
After updating to the latest version of the app, there is a bug/delay in the app launching animation and it stuck at this page for a second
![Screenshot_20231002-122718_Calculator](https://github.com/sadellie/unitto/assets/93507842/8bc9c5ad-8d41-421e-8339-33ff51312050)
I hope it will be fixed asap

**Comment by sadellie** [comment]
#92
