### ISSUE TITLE
Modulo needed

### ISSUE THREAD

**Issue by HydroRaptor** [sadellie/unitto#103]
New math operation needed [Modulo](https://en.wikipedia.org/wiki/Modulo)
for example, 345 mod 26 = 7

![image](https://github.com/sadellie/unitto/assets/98384514/b4d1b3b8-a836-4f87-8d0c-a23557331b0d)

**Comment by sadellie** [comment]
![Screenshot_20231002-135002~2.jpg](https://github.com/sadellie/unitto/assets/10384356/770069e6-f3a2-4056-8f07-756d9d398e65)

**Comment by HydroRaptor** [comment]
so # is mod 
ok thanks
