### ISSUE TITLE
Font is not uniform everywhere

### ISSUE THREAD

**Issue by Jobatphysics** [sadellie/unitto#113]
When we uses system font, then we assume that we will have system font everywhere but in calculator numerics it's not changing see attachment 
![Screenshot_20231030-194140_Calculator~2](https://github.com/sadellie/unitto/assets/94097278/81d2ab50-c768-4db6-9c09-6f7013892a7d)

**Comment by sadellie** [comment]
Disable **System font** so that button icons and text field font match

**Comment by sadellie** [comment]
Currently it's not possible due to performance issues. Buttons use hand drawn icons, not text
