### ISSUE TITLE
Tapping on an operation after calculating clears the calculated value

### ISSUE THREAD

**Issue by PalmDevs** [sadellie/unitto#117]
## Issue

Tapping on an operation button (+, -, ×, ÷) clears the calculated value meaning you can no longer chain calculations.

## Steps to reproduce

- Install the Olive Green build
- Input any equation
- Tap the = sign
- Tap any of the operation buttons
- Observe the calculated value getting cleared

## Additional context

This issue started after the Olive Green release. Pre-release builds prior did NOT have this issue.

**Comment by PalmDevs** [comment]
I have not tested any other operations other than the primary ones (eg. ^, √, ...)

**Comment by kushalarvindo** [comment]
Even I have the same issue here

**Comment by axelsimon** [comment]
I can confirm that Nadeshiko Pink (26) does not have this issue.

**Comment by kushalarvindo** [comment]
> I can confirm that Nadeshiko Pink (26) does not have this issue.

Can you try this operation-
1) Add 7+4
2) Click on "equals to"
3) Now try adding 7 to the answer (without re typing the previous answer)

Now does it work?

**Comment by axelsimon** [comment]
If I press <kbd>+</kbd> <kbd>7</kbd>, I see 18 appear as a result on the line below, slightly greyed out.
If I press <kbd>7</kbd> directly, i just see 117, with no result on the line below.
