### ISSUE TITLE
The theme color palette does not display on Android 7

### ISSUE THREAD

**Issue by Dragonfly-30** [sadellie/unitto#124]
I have a phone with android 7.0 and color palette is not showing on it. It isn't a big issue but thought of letting you know. Thank you in advance and here's a screenshot

screenshot

![WhatsApp Image 2023-11-17 at 15 51 52_3d5c438b](https://github.com/sadellie/unitto/assets/113085944/352f5d23-810c-4998-b1c1-2bc93af28af3)

**Comment by sadellie** [comment]
Intended limitation
