### ISSUE TITLE
Number Base converter

### ISSUE THREAD

**Issue by deepu2** [sadellie/unitto#14]
Implement base converter (Binary, Oct, Decimal, Hex)

**Comment by sadellie** [comment]
Hello, I have started working on this feature. Base converter will probably look like this:
<img src="https://user-images.githubusercontent.com/10384356/210153676-d5c204e1-b540-483b-8b84-2b0305bfd5dd.png" alt="drawing" width="200"/>

Calculator functionality will **not** be available in this mode (at least for now).
Supported bases: from binary to hexadecimal.

**Comment by sadellie** [comment]
Done. Will be in the next major update.

**Comment by deepu2** [comment]
Damn! Thanks for this! Will this be limited to binary and hex for now?

**Comment by sadellie** [comment]
No, I have added base2, base3, base4 and all the way up to base16. Here is a screenshot:

<img src="https://user-images.githubusercontent.com/10384356/210413048-75e0c986-41c9-4dfe-9def-303ba0ea6e4a.png" alt="drawing" width="200"/>
