### ISSUE TITLE
feature request: speed <-> pace conversions

### ISSUE THREAD

**Issue by yatzy** [sadellie/unitto#144]
Thank you for a brilliant app!

For some non-obvious reason to me all(/most?) fitness apps use pace (min/km , min/mile ) instead of speed (km/h). It would be cool if Unitto could do conversions between those!

Thank you

**Comment by VasilisKos** [comment]
> Thank you for a brilliant app!
> 
> For some non-obvious reason to me all(/most?) fitness apps use pace (min/km , min/mile ) instead of speed (km/h). It would be cool if Unitto could do conversions between those!
> 
> Thank you

That would be a great feature!

The "non obvious" reason is that all (at least long distance like me) runners use pace to control their speed throughout their run, especially after each kilometer. Checking speed while running is not so practical.
