### ISSUE TITLE
Characters in buttons flicker

### ISSUE THREAD

**Issue by edilberto507h** [sadellie/unitto#150]
How to reproduce 

Run unitto
Open left menu panel.
Select calculator or unit converter.
The calculator buttons characters start to flicker

**Comment by sadellie** [comment]
Please provide:
- video
- device name
- android version
- DPI

**Comment by edilberto507h** [comment]
https://github.com/sadellie/unitto/assets/109629876/9cbfcd52-54fc-4b18-bfb9-2a94817a30ab

Motorola G20
Android 11
DPI 280
