### ISSUE TITLE
UI implementation 

### ISSUE THREAD

**Issue by Maha-Rajan** [sadellie/unitto#157]
Hey I wanted to express my thoughts on implementing a ui/ux experience that may look cool and perhaps have a bit of functionality attached.

The Title name of what service we are currently using is shown in the top centre and there seems to be a hamburger icon on the top left just to change between the services.

I would like to see a change in which the hamburger icon is completely removed and the title is made to be a clickable action button. Upon clicking it. It expands similar to the internet toggle in the qs pannel and every other service is listed on it to choose.

This will make it a bit modern to look.

**Comment by sadellie** [comment]
Adding custom components and navigation logic will affect accessibility
