### ISSUE TITLE
Button Animation not working properly

### ISSUE THREAD

**Issue by heschy2** [sadellie/unitto#162]
In Google Calculator you can tap on a button and it temporarily transforms into a squircle (or whatever that is).

In unitto, the animation is not properly implemented: The button has to be hold in order for the animation to work. The tranformation is imideatly interrupted when the finger leaves the display. This behaiviour should only occur when the Transformation is complete:

Current:
Tap -> Not enough time to trnasform
Hold -> Transforms and detransforms when finger is lifted

Expected:
Tap -> Complete transformation with imidieate detransformation AFTER the animation completed
Hold -> current

**Comment by heschy2** [comment]
Hi, as far as I understood, the Issue was resolved and is fixed in the newest Version, however I just recieved the F-Droid Update to the Version "Quick Silver", and the Issue is still persistent.

**Comment by sadellie** [comment]
Everything works as expected. I am not developing a Google Calculator clone.

**Comment by heschy2** [comment]
Of course not, Unitto is way better than GCalc. But this animation looks weird, and design is one of the only things where cloning Google is good. The design of Unitto is already pretty "inspired" by GCalc, so the Animation does not make a real difference in that regard.

As a developer I absolutely agree that of course you can decide what Unitto should look and behave like.

But as a User, I have to tell you that this animation is weird, and doing it how google does it would improve the experience and Users would apreciate it.

But as I said, of course I respect if you decide not to do that, thats perfectly okay.
