### ISSUE TITLE
Negative times negative does not produce correct output

### ISSUE THREAD

**Issue by xfarrow** [sadellie/unitto#164]
-5 * -1 correctly shows +5.

Now
5-10 [enter]
-5 * -1 shows -5.
![Screenshot_2024-01-18-14-02-59-243_com sadellie unitto](https://github.com/sadellie/unitto/assets/49845537/d331501d-3223-4278-87e2-e3e35299587f)

**Comment by xfarrow** [comment]
Is it related to #152 ? Then I just need to wait for an upgrade. Thank you for your work.

**Comment by sadellie** [comment]
Yes, it's the same bug
