### ISSUE TITLE
Options of Accessing Unit Groups

### ISSUE THREAD

**Issue by brucetheelephant** [sadellie/unitto#178]
I think Accessing Unit Groups, and Units in Unit Groups could be improved. I think that scrolling Unit Groups (horizontal) (when you have many enabled) is a bit of a pain.

I'm not sure how this could be improved best but I'll write about some ideas that I had and you can decide if they are good or bad ideas and if they are worth implementing or not.

At the moment I think a quick improvement could be adding an option to Search for Units in all Enabled Unit Groups instead of Searching for Units only in the Active Unit Group. This could be added as a toggle (between Search in Active Unit Group and Search in All Enabled Unit Groups) and would not need a drastic interface change.

Another improvement could be making the Unit Groups List vertical. You could: click on the Unit Groups tab which would open the List of Enabled Unit Groups - click on desired Unit Group which would (slide) open (from the right) the List of Units. Users could use clicks (on buttons) or finger gestures. This would require a drastic interface change and a lot of work but it would make scrolling through options (Unit Groups and Units) vertical scrolling which would make searching easier (in my opinion).

**Comment by sadellie** [comment]
> an option to Search for Units in all Enabled Unit Groups

You can do that by clicking on selected unit group. When all unit groups are deselected, the entire list is shown (all enabled unit groups)

![image](https://github.com/sadellie/unitto/assets/10384356/cb97e2c3-6420-4630-b156-c84b72514ef3)

> making the Unit Groups List vertical

Currently testing and iterating over different versions with fewer clicks. Will start testing in Preview channel once properly implemented.
