### ISSUE TITLE
No vibration when pressing keyboard buttons

### ISSUE THREAD

**Issue by midros** [sadellie/unitto#181]
Although the haptic feedback is on, there is no vibration when keyboard buttons are pressed.

Version 36 Quick silver (although it never worked even with previous versions.)
Mobile phone Samsung Xcover 4s with Android version 11.

**Comment by sadellie** [comment]
Check Accessibility settings of your phone. Make sure **Touch feedback** is ON. If that doesn't help, you may need to contact your OS developer.

**Comment by midros** [comment]
Well, it is on and works well in all other cases...
