### ISSUE TITLE
Bug : Some times it can't shows correct ans

### ISSUE THREAD

**Issue by iBabu007** [sadellie/unitto#184]
See this
![Screenshot_20240208-214833](https://github.com/sadellie/unitto/assets/65340361/0fe752b8-1731-4d9a-a275-fcc83cd78789)

**Comment by sadellie** [comment]
300 * 100 = 30E+3 = 30 * 10^3 = 30000

You can disable **Exponential notation** in **Formatting** settings

**Comment by iBabu007** [comment]
Thanks.
