### ISSUE TITLE
Add normal calculator functionality along with unit conversion

### ISSUE THREAD

**Issue by S-Sajith** [sadellie/unitto#2]
Adding normal calculator functionlaity would make this app a great foss alternative to this app https://play.google.com/store/apps/details?id=all.in.one.calculator.
Combining both calculator and unit converter functionality is a no brainer and would negate the requirement of having seperate apps for calculator and unit conversion and would broaden the user base of this app

**Comment by sadellie** [comment]
Hello @S-Sajith, this feature request is not relevant anymore, right? Wonder why you closed it so quickly. 🤨

**Comment by S-Sajith** [comment]
> Hello @S-Sajith, this feature request is not relevant anymore, right? Wonder why you closed it so quickly. 🤨

Well I saw in another issue thread that you were not going to support the app anymore , so I was like is there any point in opening the issue . If you are willing to work on it then I will keep the issue open .

**Comment by S-Sajith** [comment]
Please add an option to disable unit conversion functionality while using unitto as a normal calculator

**Comment by sadellie** [comment]
I don't understand how this feature would benefit user. If you need a calculator functionality you can just ignore conversion results.

Also, Unitto is primarily a unit converter. With unit conversion disabled user will be left with a very primitive version of a calculator.

Competition with All-In-One Calculator is beyond the scope of this project.

**Comment by sadellie** [comment]
nvm, will implement in the future update

**Comment by sadellie** [comment]
Done. Need some UX improvements, but basic stuff is done.

<img src="https://user-images.githubusercontent.com/10384356/218312769-9089e7ad-3b85-4ac2-95bc-39be5a8ffdd1.png" alt="drawing" width="200"/>

**Comment by sadellie** [comment]
Added a very cool history view (definitely didn't steal from Google Calculator).

Calculator is now stable and useful enough for daily usage — closing this issue.

**_Thank you_** for this feature request.

P.S. Can't show you screenshots since the UI is not final yet.
