### ISSUE TITLE
Scaling on taller devices.

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [sadellie/unitto#24]
I have a Samsung Galaxy Z Flip4 which has an aspect ratio of 22:9 making it much taller than most standard phones which have an aspect ratio of either 19.3:9, 19.5:9 or 20:9. The issue is that the buttons for that calculator are stretched vertically quite a bit (see image below) and make them much larger than they need to be and kind of make the app a little uncomfortable to use.

![Screenshot_20230301_111734_Unitto](https://user-images.githubusercontent.com/82244192/222245943-3199ec85-5e51-44b1-8591-550dd68c01d6.jpg)

**Comment by sadellie** [comment]
Added to backlog. Will see what can I do about comically tall devices.

**Comment by sadellie** [comment]
@LovecraftianGodsKiller What display size do you use? Everything looks way too small.

I mean this "display size":
<img width="34%" src="https://user-images.githubusercontent.com/10384356/222824423-6e6eb554-3937-4975-bf53-9612820cc279.png" />

**Comment by LovecraftianGodsKiller** [comment]
I change my display value by going into the developer options and changing the dpi. The dpi value I always set is 597.

**Comment by LovecraftianGodsKiller** [comment]
The smallest display size that can be set normally is still too big for me. I like having everything much smaller than normal
