### ISSUE TITLE
[Enhancement] Can you add electrical converter of capacitor and etc

### ISSUE THREAD

**Issue by hardcorp74** [sadellie/unitto#28]
Can you add electrical converter of capacitor and etc

**Comment by sadellie** [comment]
Do you mean farad, kilofarad and other units?

**Comment by hardcorp74** [comment]
yes. pico nano micro etc

and maybe useful this case in program interface
**Expand button** "All" or similar button
where there will be a listing with all translations of values
calculated from the main one
