### ISSUE TITLE
[Enhancement] More conversions 

### ISSUE THREAD

**Issue by endresmartin** [sadellie/unitto#29]
Can you add more conversions to your converter?

- [x] Fuel consumption (L/100km, km/l, mi/l, Mpg (US), mpg (Brit), gal/100mi)
- [x] Force (N, lbf, otf, kp)
- [x] Torque
- [x] Flow rate
- [x] Luminescence

**Comment by RamPawar7** [comment]
Time conversion (EST to GST, etc.)

**Comment by sadellie** [comment]
@RamPawar7 

Do you mean like this?
https://timezoneconverterapp.com/

If so, open a new issue, because that's gonna be a separate screen/tool, not a part of Unit Converter.
