### ISSUE TITLE
Multi language support 

### ISSUE THREAD

**Issue by wmdhs12138** [sadellie/unitto#3]
Is there any plan for multilingual support, which can be participated by other contributors？

**Comment by sadellie** [comment]
Hello! Yes, I have plans on setting up POEditor for translations. It probably will not happen this month, most likely January.

**Comment by Ilithy** [comment]
Hi, both are good, but POEditor is more respectful towards the developer, it is also quite easy to use, and free for FOSS projects

Can we send you the translations via PR? or do we have to open an issue here first?

Thanks very much

**Comment by sadellie** [comment]
POEDitor project is live. Currently added 5 languages: 
* English US
* English UK
* German
* French
* Russian

Link: https://poeditor.com/join/project/T4zjmoq8dx

Also added badge in ***README*** https://github.com/sadellie/unitto#translate
