### ISSUE TITLE
Numbers' shape 

### ISSUE THREAD

**Issue by spdt97** [sadellie/unitto#34]
Just a suggestion, make numbers more roundy! Like this...
![Screenshot_20230331-004017_Unitto](https://user-images.githubusercontent.com/128099488/228939603-753e306a-0fca-4cb8-aafe-f21a639fd12e.png)

**Comment by sadellie** [comment]
Similar to #24. It will be fixed after stuff in [feature/responsive-ui](https://github.com/sadellie/unitto/tree/feature/responsive-ui) are ready for merge.

To fix UI elements size issue Unitto will follow Google's solution. For example, text fields container (the one you drag down) is always taking 25% of the screen height.

Here are the results (not final):

![image](https://user-images.githubusercontent.com/10384356/228946086-df0e22b1-e8e7-4917-855e-7f5cc5f6c04c.png)

_**Thank you**_ for reporting this issue.
