### ISSUE TITLE
Add an AC button

### ISSUE THREAD

**Issue by Hidetoshi6721** [sadellie/unitto#41]
Instead of
![Screenshot_20230413-194949~3](https://user-images.githubusercontent.com/85873175/231794607-56729eef-64f5-49ee-a657-b0f9d881f646.png)

Add
![Screenshot_20230413-200909-015](https://user-images.githubusercontent.com/85873175/231794860-eb927c4a-31a8-4921-b4ca-420045a111dd.png)

(As in GCalc.)
I really miss the AC button...

**Comment by sadellie** [comment]
Will probably be added as a side effect for other unrelated feature.

**Comment by rencornationers** [comment]
I miss AC too :(

**Comment by crse** [comment]
> I don't think that's necessary. You can press the delete button for half a second and it will do the same thing. There is no point in making a duplicate.

That half second can add a lot, especially when you use the app for use case like grading school exam, counting price in warehouse, etc.

I had to install another calculator app for exact reason.

**Comment by Satwik055** [comment]
I can get started with this feature right away, can you assign it to me ?
