### ISSUE TITLE
Factorial of pi calculation

### ISSUE THREAD

**Issue by Hidetoshi6721** [sadellie/unitto#44]
![Screenshot_20230414-142517](https://user-images.githubusercontent.com/85873175/231997086-69b565d2-1ac8-4b1a-9217-cf57fd5ce409.png)

How does π! = 6?
Fyi, GCalc returns a "Domain Error"...

**Comment by sadellie** [comment]
No control over this

**Comment by sadellie** [comment]
Probably will be fixed as a side effect of another feature.
