### ISSUE TITLE
NaN when doing mathematical operations

### ISSUE THREAD

**Issue by HotarunIchijou** [sadellie/unitto#47]
When I doing any mathematical operations, there's NaN below this when I didn't even finish typing what I want to do
![](https://user-images.githubusercontent.com/113282550/232285616-c013e65d-11fd-4507-bf5a-d09876f94928.png)

**Comment by sadellie** [comment]
Will not display NaN at all now. In the future will try to add proper error handling after clicking "=" (like in GCalc).
