### ISSUE TITLE
Splash screen following app theme

### ISSUE THREAD

**Issue by tsiflimagas** [sadellie/unitto#50]
Your app is a real eye candy! The only thing that sometimes bothers me a little though is the splash screen. That grey background doesn't look that good when the app theme is light. I've noticed that on some of my apps the background of the splash screen not only follows the app theme but it follows even Material You colors. That would be even better than just light/dark I believe, if you could make it.

**Comment by sadellie** [comment]
## Done.

- Devices with **Android 12** and higher will use Material You colors.
- **Older devices** will use white (`#FFFFFF`) and "almost" black (`#1B1B1B`) colors.

### Note:
- You will see light colored splash screen even if you set the app to use dark theme. it's intended by Android itself.
