### ISSUE TITLE
Unmathematical percentage support

### ISSUE THREAD

**Issue by IT-Tool** [sadellie/unitto#52]
The calculator doesn't calculate the interest correctly.

![Screenshot_20230504.jpg](https://user-images.githubusercontent.com/53435741/236058898-ceb6478e-08ff-49f0-af42-af2c7dc445f3.jpg)

**Comment by Hidetoshi6721** [comment]
Well, in general sense, it's correct, right?
125 + 9% = 125 + 0.09 = 125.09

Only GCalc does the hard work for you:
125 + 9% of 125 = 125 + 11.25 = 136.25

Unitto will give the correct answer for
**125+9%×125**

**Comment by Ilithy** [comment]
Hi,
The correct answer is 125 + 9% = 125 x 0.009 = 11.25 + 125 = 136.25

**Comment by sadellie** [comment]
![image](https://github.com/sadellie/unitto/assets/10384356/95d914a7-60b8-40b1-8058-90434151942f)

**Comment by sadellie** [comment]
> > ![image](https://github.com/sadellie/unitto/assets/10384356/95d914a7-60b8-40b1-8058-90434151942f)
> > 
> 
> where is the update?

Soon™

(probably this week)
