### ISSUE TITLE
Slow to open

### ISSUE THREAD

**Issue by Drangonfly30** [sadellie/unitto#54]
Maybe it's not an issue as my phone is already quite old but still thought of sharing that it takes a lot of time in opening, even more than google calculator while opencalc opens immediately.

**Comment by sadellie** [comment]
Recent commits that improve **cold** startup time:
* f25af1caadae9a38b6d89371257a4a2b956ca7d9
* 8f1847618a7f9d48af9f665f90aed462d7747c56
* 62af6a5ba274254b68795434740e6aea6ea721bb

Note: Unitto will always have a longer **cold** startup time than mentioned calculators.
