### ISSUE TITLE
wrong bytes conversion

### ISSUE THREAD

**Issue by Anuj-Yadav-Git** [sadellie/unitto#66]
it shows 1000 byte = 1 kilobyte. it should be 1024 byte = 1 kilobyte. same for other byte units

**Comment by sadellie** [comment]
SI standard:

1kilobyte = 1000 byte
1 kibibyte = 1024 byte

**Comment by Anuj-Yadav-Git** [comment]
my bad

**Comment by Anuj-Yadav-Git** [comment]
delete this shit
