### ISSUE TITLE
[Bug] Unit converter for time is strange

### ISSUE THREAD

**Issue by Myzel394** [sadellie/unitto#72]
When you convert a time, for example 2 hours into minutes, I'd assume it to show "120" minutes, but it shows "2h" instead..... well I know that "2 hours" is "2h" :D

![20230629_115846_temp](https://github.com/sadellie/unitto/assets/50424412/4a0ed063-99f8-454d-8774-7f17e8ac6e1f)

**Comment by Myzel394** [comment]
Also if you try to convert "20 minutes" into hours, you get really strange results

**Comment by sadellie** [comment]
Settings -> Format time

**Comment by Myzel394** [comment]
Ahh I see, however, I'd recommend that this setting does not apply when you convert a time, because it doesn't make sense then :O
