### ISSUE TITLE
[Enhancement] Percentage/Discount Calculator

### ISSUE THREAD

**Issue by stephenjudge** [sadellie/unitto#73]
I'd really like it if you had a tool in the app that could calculate the price of something after a percentage discount has been applied.

So when I'm in a store and they have sale with 25% off labeled prices, in the app I could enter the labeled price and the percentage discount, and it would then tell me what the end price would by.

As an aside I'd imagine something similar might be useful for calculating the true price of something when sales tax is applied. For example in some US States the price on product labels does not include the sales tax which is added at the checkout when you go to pay.

**Comment by sadellie** [comment]
You can use percentages in calculator. 

Do you think a separate tool is needed? What are the benefits?

![Screenshot_20230803-195402.jpg](https://github.com/sadellie/unitto/assets/10384356/76bcddc0-4d86-4e69-9e62-4f9804e76398)
