### ISSUE TITLE
Delay in history

### ISSUE THREAD

**Issue by BabyOilJohnson** [sadellie/unitto#75]
There is a delay while swiping up/closing the history page.

**Comment by BabyOilJohnson** [comment]
Thanks for the fix. But there is a small problem, when swiping up the history page doesn't completely close leaves a short portion there.
![Screenshot_20230904-135613_Calculator](https://github.com/sadellie/unitto/assets/101601874/15972e75-43d2-4fe3-a2a8-1bfe043d2acc)

**Comment by sadellie** [comment]
Can you swipe up more to completely close it?

**Comment by BabyOilJohnson** [comment]
I tried but I had to hold and drag up to close, can't close it by a single swipe.

**Comment by sadellie** [comment]
It's a sort of intended behavior. You should be able to close by single swipe if you drag more. I will try to adjust the gesture so that it's easier to swipe
