### ISSUE TITLE
Change language setting

### ISSUE THREAD

**Issue by fievel** [sadellie/unitto#77]
Hello, one useful missing feature IMHO would be to have a setting to control the application language as many applications have. 

I contribute to the French translation that I like to use in "personal" use case but for "professional" use, as I work 90% of the time in English, it would be nice to be able to restart the application in English in order to not have to mentally translate unit names. 

Also sometimes people just don't like the translation or prefer to use another language than their device one (I know there is a per application language setting in most recent android version but not everyone have an up-to-date version)

**Comment by inson1** [comment]
Where do you plan to get the translations?

**Comment by inson1** [comment]
What platform do you plan using for getting the translations?

**Comment by sadellie** [comment]
https://github.com/sadellie/unitto?tab=readme-ov-file#-translate

**Comment by inson1** [comment]
@sadellie Thank you and sorry. I havent noticed that.
