### ISSUE TITLE
Support for custom fonts

### ISSUE THREAD

**Issue by krishna8755** [sadellie/unitto#81]
I have applied a custom font on my device. But in the app it is on system default font. The team can bring support for custom fonts.

**Comment by BabyOilJohnson** [comment]
I tested this on preview version but the app still only use the stock font(I think), not the currently applied device font.

**Comment by BabyOilJohnson** [comment]
@sadellie can this doable to numbers in the numpad.

**Comment by sadellie** [comment]
> @sadellie can this doable to numbers in the numpad?

No, numpad buttons use icons (not a real text)

**Comment by krishna8755** [comment]
Thanks for bringing my suggestion to the app. Though in app settings custom fonts are supported, in num pad they are not supported. I got to know from the replies that it's because, they use icons not text. I want to know is not there a way to use texts instead of icons. I have given an example in the image of Samsung calculator in which custom fonts are supported in the numpad.
![_4a3f3816-b345-410a-9fb7-50ae30fb5b68](https://github.com/sadellie/unitto/assets/138577902/c9911953-d370-4ab5-988f-414f9f22f428)
![20230909_134322_0000](https://github.com/sadellie/unitto/assets/138577902/77046cc4-cb62-47c0-8e78-97144fb0f79d)
[](url)

**Comment by krishna8755** [comment]
Thanks for bringing my suggestion to the app. Though in app settings custom fonts are supported, in num pad they are not supported. I got to know from the replies that it's because, they use icons not text. I want to know is not there a way to use texts instead of icons. I have given an example in the image of Samsung calculator in which custom fonts are supported in the numpad.
![WhatsApp Image 2023-10-08 at 12 15 44 PM](https://github.com/sad
![WhatsApp Image 2023-10-08 at 12 15 44 PM (1)](https://github.com/sadellie/unitto/assets/138577902/91379152-b77c-42a1-97ee-adfe6fb71677)
ellie/unitto/assets/138577902/e6dbcb6b-5d08-4ede-9022-afb500b43759)

**Comment by krishna8755** [comment]
Thanks for bringing my suggestion to the app. Though in app settings custom fonts are supported, in num pad they are not supported. I got to know from the replies that it's because, they use icons not text. I want to know is not there a way to use texts instead of icons. I have given an example in the image of Samsung calculator in which custom fonts are supported in the numpad.
![WhatsApp Image 2023-10-08 at 12 15 44 PM](https://github.com/sadellie/unitto/assets/138577902/70a96b07-a00a-4777-a444-7a1641d3120f)
