### ISSUE TITLE
Support reproducible builds for F-Droid

### ISSUE THREAD

**Issue by FineFindus** [sadellie/unitto#87]
Add support for publishing [F-Droid reproducible builds](https://f-droid.org/docs/Reproducible_Builds/). This allows users to update the app from other sources than just F-Droid, which can be helpful for bug fix releases.

**Comment by sadellie** [comment]
Clarification for anyone interested. 

1. I'm not confident in my build setup. It will probably be time consuming to support reproducible builds.
2. I have added an option to Export/Import user data. Users can now easily switch from GitHub to F-Droid build.
3. I don't want to spend F-Droid's team resources on fixing reproducible builds for this project.
