### ISSUE TITLE
Support comma as decimal separator without dots

### ISSUE THREAD

**Issue by GrimPixel** [sadellie/unitto#90]
In the current settings, the comma is the decimal separator, only when the dot is used for groupping.
There should be two settings: Decimal separator and group separator, and the two are not allowed to be the same.

**Comment by kanlukasz** [comment]
Yes, I just tried the Unitto app and this option is definitely missing. In Poland we use this format, eg with currency:
100,00 PLN
10 000,00 PLN
100 000,00 PLN
etc...
