### ISSUE TITLE
App crashes when manually selecting theme color

### ISSUE THREAD

**Issue by adarsh1001** [sadellie/unitto#99]
**Steps to reproduce**
1. Go to app Settings > Display.
2. Uncheck Dynamic colors.
3. Select a color other than the first one.
4. The app will crash.

**Additional observation**
Moving from the first color to any other crashes the app. Moving among the other colors once recovered doesn't result in a crash.

**Screencap**
https://github.com/sadellie/unitto/assets/8820038/53190f7a-7ddd-420a-ac5f-05855713cf13

**Device info**
OS: Android 13
Device: Nothing Phone (2)
App Version: 撫子Pink

**Comment by sadellie** [comment]
Fixed in **Nadeshiko Pink (26)**
